[package]
name = "mal-rust"
version = "0.47.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.4"
rustyline = "9.1.2"

[dev-dependencies]
gag = "1.0.0"
